### ISSUE TITLE
Help to run it locally

### ISSUE THREAD

**Issue by AdityasahuX07** [CharlesXstorm/netflixClone#36]
Hi you made great clone can you help  me to setup it locally I did as staps mentioned in github page the page loads the login page shows but when I try to login by click "Sign-ln as a Guest" I not able to login and stayed in same page 

please help me to resolve

**Comment by CharlesXstorm** [comment]
Hello 😊, did you create a mongodb URI and place it in your .env file as stated?

- apart from the guest sign-in, is your signup and login working?

- also, the guest sign-in won't work if you don't have a guest account in your database.
So, you need to first signUp a guest account before you can sign-in as guest.

Use this specific email and password when signing up the guest account:

Email: guest@conflix.com
Password: 123456

After signing up the guest account, the sign-in as guest button should now work.

Try this and let me know if you run into any other issues.


> Hi you made great clone can you help  me to setup it locally I did as staps mentioned in github page the page loads the login page shows but when I try to login by click "Sign-ln as a Guest" I not able to login and stayed in same page 
> 
> please help me to resolve

**Comment by AdityasahuX07** [comment]
its says the password is weak and even I put previously created username and password which present in database URL still not able to login what is the problem 

![Image](https://github.com/user-attachments/assets/cf8d1f22-b2c0-47d9-8a7b-b087c6d5167f)

**Comment by AdityasahuX07** [comment]
these is the log for error identification 

D:\Conflix\server>npm run dev

> netflix@1.0.0 dev
> concurrently --kill-others-on-fail "npm run server" "npm run client"

(node:29384) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[0]
[0] > netflix@1.0.0 server
[0] > nodemon server.js
[0]
[1]
[1] > netflix@1.0.0 client
[1] > npm run dev --prefix ../client
[1]
[0] [nodemon] 3.1.0
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,cjs,json
[0] [nodemon] starting `node server.js`
[1]
[1] > client@0.0.0 dev
[1] > vite
[1]
[1]
[1]   VITE v5.4.15  ready in 674 ms
[1]
[1]   ➜  Local:   http://localhost:5173/
[1]   ➜  Network: use --host to expose
[0] server started on port 5173
[0] node:internal/dns/callback_resolver:45
[0]     this.callback(new DNSException(err, this.bindingName, this.hostname));
[0]                   ^
[0]
[0] Error: queryTxt EREFUSED cluster1.tgl1vxa.mongodb.net
[0]     at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/callback_resolver:45:19) {
[0]   errno: undefined,
[0]   code: 'EREFUSED',
[0]   syscall: 'queryTxt',
[0]   hostname: 'cluster1.tgl1vxa.mongodb.net'
[0] }
[0]
[0] Node.js v22.14.0
[0] [nodemon] app crashed - waiting for file changes before starting...
[1] DEPRECATION WARNING [legacy-js-api]: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
[1]
[1] More info: https://sass-lang.com/d/legacy-js-api
[1]
[1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
[1] Use math.random instead.
[1]
[1] More info and automated migrator: https://sass-lang.com/d/import
[1]
[1]     ╷
[1] 277 │                     animation-delay: calc(random(200) / 100) + s
[1]     │                                           ^^^^^^^^^^^
[1]     ╵
[1]     src\components\UI\ConflixIntroAnim\style.sass 277:28  root stylesheet
[1]
[1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
[1] Use math.random instead.
[1]
[1] More info and automated migrator: https://sass-lang.com/d/import
[1]
[1]     ╷
[1] 279 │                         left: percentage(calc(random(200) / 100))
[1]     │                                               ^^^^^^^^^^^
[1]     ╵
[1]     src\components\UI\ConflixIntroAnim\style.sass 279:29  root stylesheet
[1]
[1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
[1] Use math.percentage instead.
[1]
[1] More info and automated migrator: https://sass-lang.com/d/import
[1]
[1]     ╷
[1] 279 │                         left: percentage(calc(random(200) / 100))
[1]     │                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]     ╵
[1]     src\components\UI\ConflixIntroAnim\style.sass 279:13  root stylesheet
[1]
[1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
[1] Use math.random instead.
[1]
[1] More info and automated migrator: https://sass-lang.com/d/import
[1]
[1]     ╷
[1] 280 │                         animation-delay: calc(random(200) / 100) + s
[1]     │                                               ^^^^^^^^^^^
[1]     ╵
[1]     src\components\UI\ConflixIntroAnim\style.sass 280:29  root stylesheet
[1]
[1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
[1] Use math.random instead.
[1]
[1] More info and automated migrator: https://sass-lang.com/d/import
[1]
[1]     ╷
[1] 285 │                     animation-delay: calc(random(200) / 100) + s
[1]     │                                           ^^^^^^^^^^^
[1]     ╵
[1]     src\components\UI\ConflixIntroAnim\style.sass 285:28  root stylesheet
[1]
[1] WARNING: 107 repetitive deprecation warnings omitted.
[1]

**Comment by AdityasahuX07** [comment]
server .env

NODE_ENV = development
PORT = 5173
DATABASE= mongodb+srv://Aditya007:cvo123456@cluster1.tgl1vxa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
USER= Aditya007
DATABASE_PASSWORD = cvo123456
JWT_SECRET = 7iR2Y9HMz2pyyZ3ckUwqOChP_1262Lf9tr5UDSZ-7V4
TMDB_AUTH = 01f2ed53e66591fa41dac39
TMDB_URL = https://api.themoviedb.org/3

client .env

VITE_TMDB_AUTH = 01f2ed53e66591fa41dac39
VITE_TMDB_URL = https://api.themoviedb.org/3
VITE_API_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vbG9jYWxob3N0Ojo1MTczIjoiL2FwaS92MS9jb25mbGl4In0.XlX_LNbFbUKwIemt7ZBv1aPuvqBS3oKVjXyFtnX5oTs
VITE_API_URL = /proxy/api/v1/conflix/users
VITE_PROXY_URL = http://localhost:5173/
VITE_GEOLOCATION_URL = https://api.country.is/

**Comment by CharlesXstorm** [comment]
> its says the password is weak and even I put previously created username and password which present in database URL still not able to login what is the problem 
> 
> ![Image](https://github.com/user-attachments/assets/cf8d1f22-b2c0-47d9-8a7b-b087c6d5167f)

No, this isn't where you'd sign up the guest account.

I was talking about signing up the guest account on the conflix website.

The username and password for your mongodb should not be shared.
It's a personal thing.
Your mongodb username and password can be anything. 
It's used by the app to access your database.

**Comment by CharlesXstorm** [comment]
The app is not accessing your database.
It needs to have access to your database before anything can work.

> these is the log for error identification 
> 
> D:\Conflix\server>npm run dev
> 
> > netflix@1.0.0 dev
> > concurrently --kill-others-on-fail "npm run server" "npm run client"
> 
> (node:29384) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> [0]
> [0] > netflix@1.0.0 server
> [0] > nodemon server.js
> [0]
> [1]
> [1] > netflix@1.0.0 client
> [1] > npm run dev --prefix ../client
> [1]
> [0] [nodemon] 3.1.0
> [0] [nodemon] to restart at any time, enter `rs`
> [0] [nodemon] watching path(s): *.*
> [0] [nodemon] watching extensions: js,mjs,cjs,json
> [0] [nodemon] starting `node server.js`
> [1]
> [1] > client@0.0.0 dev
> [1] > vite
> [1]
> [1]
> [1]   VITE v5.4.15  ready in 674 ms
> [1]
> [1]   ➜  Local:   http://localhost:5173/
> [1]   ➜  Network: use --host to expose
> [0] server started on port 5173
> [0] node:internal/dns/callback_resolver:45
> [0]     this.callback(new DNSException(err, this.bindingName, this.hostname));
> [0]                   ^
> [0]
> [0] Error: queryTxt EREFUSED cluster1.tgl1vxa.mongodb.net
> [0]     at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/callback_resolver:45:19) {
> [0]   errno: undefined,
> [0]   code: 'EREFUSED',
> [0]   syscall: 'queryTxt',
> [0]   hostname: 'cluster1.tgl1vxa.mongodb.net'
> [0] }
> [0]
> [0] Node.js v22.14.0
> [0] [nodemon] app crashed - waiting for file changes before starting...
> [1] DEPRECATION WARNING [legacy-js-api]: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
> [1]
> [1] More info: https://sass-lang.com/d/legacy-js-api
> [1]
> [1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
> [1] Use math.random instead.
> [1]
> [1] More info and automated migrator: https://sass-lang.com/d/import
> [1]
> [1]     ╷
> [1] 277 │                     animation-delay: calc(random(200) / 100) + s
> [1]     │                                           ^^^^^^^^^^^
> [1]     ╵
> [1]     src\components\UI\ConflixIntroAnim\style.sass 277:28  root stylesheet
> [1]
> [1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
> [1] Use math.random instead.
> [1]
> [1] More info and automated migrator: https://sass-lang.com/d/import
> [1]
> [1]     ╷
> [1] 279 │                         left: percentage(calc(random(200) / 100))
> [1]     │                                               ^^^^^^^^^^^
> [1]     ╵
> [1]     src\components\UI\ConflixIntroAnim\style.sass 279:29  root stylesheet
> [1]
> [1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
> [1] Use math.percentage instead.
> [1]
> [1] More info and automated migrator: https://sass-lang.com/d/import
> [1]
> [1]     ╷
> [1] 279 │                         left: percentage(calc(random(200) / 100))
> [1]     │                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [1]     ╵
> [1]     src\components\UI\ConflixIntroAnim\style.sass 279:13  root stylesheet
> [1]
> [1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
> [1] Use math.random instead.
> [1]
> [1] More info and automated migrator: https://sass-lang.com/d/import
> [1]
> [1]     ╷
> [1] 280 │                         animation-delay: calc(random(200) / 100) + s
> [1]     │                                               ^^^^^^^^^^^
> [1]     ╵
> [1]     src\components\UI\ConflixIntroAnim\style.sass 280:29  root stylesheet
> [1]
> [1] DEPRECATION WARNING [global-builtin]: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
> [1] Use math.random instead.
> [1]
> [1] More info and automated migrator: https://sass-lang.com/d/import
> [1]
> [1]     ╷
> [1] 285 │                     animation-delay: calc(random(200) / 100) + s
> [1]     │                                           ^^^^^^^^^^^
> [1]     ╵
> [1]     src\components\UI\ConflixIntroAnim\style.sass 285:28  root stylesheet
> [1]
> [1] WARNING: 107 repetitive deprecation warnings omitted.
> [1]
>

**Comment by CharlesXstorm** [comment]
You shouldn't share the informations in your .env file.
It's meant to be a secret.

- The two variables "USER" and "DATABASE_PASSWORD" should be thesame as the username and password that will be used to access your database. 

i.e the username and password in the mongodb screenshot you sent.

> server .env
> 
> NODE_ENV = development
> PORT = 5173
> DATABASE= mongodb+srv://Aditya007:cvo123456@cluster1.tgl1vxa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
> USER= Aditya007
> DATABASE_PASSWORD = cvo123456
> JWT_SECRET = 7iR2Y9HMz2pyyZ3ckUwqOChP_1262Lf9tr5UDSZ-7V4
> TMDB_AUTH = 01f2ed53e66591fa41dac39
> TMDB_URL = https://api.themoviedb.org/3
> 
> client .env
> 
> VITE_TMDB_AUTH = 01f2ed53e66591fa41dac39
> VITE_TMDB_URL = https://api.themoviedb.org/3
> VITE_API_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vbG9jYWxob3N0Ojo1MTczIjoiL2FwaS92MS9jb25mbGl4In0.XlX_LNbFbUKwIemt7ZBv1aPuvqBS3oKVjXyFtnX5oTs
> VITE_API_URL = /proxy/api/v1/conflix/users
> VITE_PROXY_URL = http://localhost:5173/
> VITE_GEOLOCATION_URL = https://api.country.is/

**Comment by AdityasahuX07** [comment]
The .env is not same i altered actual  passwod

**Comment by AdityasahuX07** [comment]
The user and password  is same but

**Comment by AdityasahuX07** [comment]
Can you share  me tutorial video

**Comment by CharlesXstorm** [comment]
> Can you share  me tutorial video 

Okay, no problem. I'll do that when I'm home.

**Comment by CharlesXstorm** [comment]
There's one important detail I forgot to mention about how your mongodb URL should look like.

DATABASE= mongodb+srv://<username<username>>:<password<password>> @cluster0.kqwa2.mongodb.net/databaseName?retryWrites=true&w=majority&appName=Cluster0

Note the database name placement within the URL. This should be replaced with the actual name of your database.
Also, the <username<username>> and <password<password>> should be literally written as is. The code in the server.js will replace the actual username and password.

I've updated the steps in the READme file to reflect this detail.

**Comment by AdityasahuX07** [comment]
Ok when u reach home  and free  please share tutorial screen recording video
Thankyou for your effort in advance.

**Comment by AdityasahuX07** [comment]
I resolved this error "Error: querySrv EREFUSED _mongodb._tcp.cluster1.tgl1vxa.mongodb.net"

 this message show - Database connected successfully

but still not able to login

**Comment by CharlesXstorm** [comment]
> I resolved this error "Error: querySrv EREFUSED _mongodb._tcp.cluster1.tgl1vxa.mongodb.net"
> 
>  this message show - Database connected successfully
> 
> but still not able to login

Sorry, I didn't have time to make the screen recording. 

The app is connecting to your database now.

-Run the app and on the homepage, click on getting started. 
-Create an account. This account will be stored on your database. 
-You would be logged in after creating the account. 
-You can then subsequently login with that account information using the other sign-in button above the "sign-in as guest" button

-For the guest account, click on getting started on the homepage.
-create an account with this specific account information:
Email: guest@conflix.com
Pass: 123456
-After successfully creating this account, the guest login should now work

**Comment by AdityasahuX07** [comment]
see what I doing wrong 

https://github.com/user-attachments/assets/bb9bcab8-1e8b-4597-960f-db2ca0e394c4

**Comment by CharlesXstorm** [comment]
> see what I doing wrong 
> 
> https://github.com/user-attachments/assets/bb9bcab8-1e8b-4597-960f-db2ca0e394c4

-After you click the Next button on the create account page, you should wait for it to sign you in.
-Also check your database to see the account you created is being stored

**Comment by AdityasahuX07** [comment]
in data base acount not created  

new error - (node:17856) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

![Image](https://github.com/user-attachments/assets/a646a2f2-54f3-45f6-a44f-e01c4b0d9de5)


{"status":"fail","message":"API Authorization failed"}

**Comment by AdityasahuX07** [comment]
Or can u you upgrade this project to Google firebase that works well without any issues

**Comment by AdityasahuX07** [comment]
in login page step 1 of 2 clicking NEXT not go to step 2 stayed on same page

**Comment by CharlesXstorm** [comment]
> in login page step 1 of 2 clicking NEXT not go to step 2 stayed on same page 

I'm creating a video instruction already.
Once I'm done, I'll let u know.

**Comment by AdityasahuX07** [comment]
Ok

**Comment by AdityasahuX07** [comment]
Please  also mention  Mongodb website setup and required settings

**Comment by CharlesXstorm** [comment]
> Please also mention Mongodb website setup and required settings

I'm done with the video.

I also made some updates to some outdated dependencies, so delete your copy of the project and re-clone it again.

Here's the link to the video: 
https://youtu.be/0z7cNlqHZfE?si=3EPfNgEm2RGkXva_
